### PR TITLE
Add listener on NumberProgressBar

### PR DESCRIPTION
**Pull request by lelexxx**

### CODE REVIEW

**Comment by daimajia** [comment]
this is a not good design.

**Comment by lelexxx** [comment]
What do you mean by "bad design" ? (design pattern, format code...)

**Comment by daimajia** [comment]
`OnProgressBarListener ` only has `onProgressBarFinish ` method, this can only solve the specific scene problem rather than the most.

**Comment by daimajia** [comment]
A good idea is `onProgressChange(int current, int total)` method.

**Comment by lelexxx** [comment]
Thanks for your reply. I will work on it and make it better.

**Comment by lelexxx** [comment]
@daimajia have you got some news ?

**Comment by daimajia** [comment]
@lelexxx So sorry for my late. Too many email everyday. 

This is a better design, thanks for working on this project :-D

**Pull request merged**
